# Prettier configuration
# https://prettier.io/docs/en/configuration.html
printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: "all"
bracketSpacing: true
bracketSameLine: true
arrowParens: "avoid"
singleAttributePerLine: true
